const ExcelJS=require('exceljs');
const Product=require('../models/Product'),Order=require('../models/Order'),Coupon=require('../models/Coupon');
const storage=require('./supabaseStorageService');
const ACTIONS=new Set(['ADD','UPDATE','DELETE','SKIP']);
const configs={
 Products:{model:Product,key:'legacyId',headers:['action','legacyId','sku','productCode','slug','name','shortDescription','description','category','subCategory','tagsJson','price','oldPrice','currency','stock','reservedStock','minOrderQty','maxOrderQty','active','featured','buyNowEnabled','addToCartEnabled','selfPickupAvailable','homeDeliveryAvailable','codAvailable','pickupLocationIdsJson','allowBackorder','badge','primaryImageJson','galleryJson','featuresJson','specificationsJson','weight','dimensionsJson','taxRate','hsnCode','createdAt','updatedAt','fullDocumentJson']},
 Orders:{model:Order,key:'orderId',headers:['action','orderId','customerId','customerName','customerMobile','customerEmail','customerAddress','customerPincode','itemsJson','subtotal','discount','couponCode','shippingCharge','taxAmount','grandTotal','currency','deliveryMode','pickupLocationId','pickupSnapshotJson','paymentMethod','paymentStatus','orderStatus','confirmedAt','inventoryCommittedAt','invoiceId','customerVisibleNote','adminNote','idempotencyKey','trackingDetails','trackingHistoryJson','feedback','reviewText','feedbackTimestamp','paymentId','createdAt','updatedAt','fullDocumentJson']},
 Coupons:{model:Coupon,key:'code',headers:['action','code','type','value','minOrder','maxDiscount','usageLimit','perCustomerLimit','usageCount','applicableProductIdsJson','applicableCategoryIdsJson','startAt','expiresAt','active','createdAt','updatedAt','fullDocumentJson']}
};
const plain=x=>{const y={...x};delete y.__v;return y};
const j=x=>x==null?'':JSON.stringify(x);
function exportRow(name,doc){const d=plain(doc);if(name==='Products')return{action:'SKIP',...d,tagsJson:j(d.tags),pickupLocationIdsJson:j(d.pickupLocationIds),primaryImageJson:j(d.primaryImage),galleryJson:j(d.gallery),featuresJson:j(d.features),specificationsJson:j(d.specifications),dimensionsJson:j(d.dimensions),fullDocumentJson:j(d)};
 if(name==='Orders')return{action:'SKIP',...d,customerId:d.customerId||'',customerName:d.customerSnapshot?.name||'',customerMobile:d.customerSnapshot?.mobile||'',customerEmail:d.customerSnapshot?.email||'',customerAddress:d.customerSnapshot?.address||'',customerPincode:d.customerSnapshot?.pincode||'',itemsJson:j(d.items),pickupSnapshotJson:j(d.pickupSnapshot),trackingHistoryJson:j(d.trackingHistory),fullDocumentJson:j(d)};
 return{action:'SKIP',...d,applicableProductIdsJson:j(d.applicableProductIds),applicableCategoryIdsJson:j(d.applicableCategoryIds),fullDocumentJson:j(d)} }
function addSheet(wb,name,rows){const h=configs[name].headers,ws=wb.addWorksheet(name);ws.columns=h.map(k=>({header:k,key:k,width:Math.max(12,Math.min(42,k.length+4))}));ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF232F3E'}};ws.views=[{state:'frozen',ySplit:1}];ws.autoFilter={from:'A1',to:ws.getRow(1).getCell(h.length).address};rows.forEach(r=>ws.addRow(r));ws.getColumn('action').eachCell((c,i)=>{if(i>1)c.value='SKIP'});ws.getColumn('action').dataValidation={type:'list',allowBlank:false,formulae:['"ADD,UPDATE,DELETE,SKIP"']};}
async function backup(){const wb=new ExcelJS.Workbook();wb.creator='AutoClickerMouse Admin';const docs=await Promise.all([Product.find().lean(),Order.find().lean(),Coupon.find().lean()]);['Products','Orders','Coupons'].forEach((n,i)=>addSheet(wb,n,docs[i].map(d=>exportRow(n,d))));const readme=wb.addWorksheet('Instructions');[['SAFE EXCEL RESTORE'],['Set action on each row: ADD, UPDATE, DELETE or SKIP.'],['Only that row is affected. Blank action is rejected.'],['Products primary key: legacyId'],['Orders primary key: orderId'],['Coupons primary key: code'],['ADD fails if key exists. UPDATE/DELETE fail if key does not exist.'],['Do not change primary keys during UPDATE.'],['fullDocumentJson preserves every database field and nested value.']].forEach(r=>readme.addRow(r));readme.getColumn(1).width=100;return wb.xlsx.writeBuffer()}
const value=(row,map,k)=>row.getCell(map[k]).value;
const parse=(v,fallback)=>{if(v==null||v==='')return fallback;if(typeof v==='object'&&!Array.isArray(v)&&v.text)return JSON.parse(v.text);if(typeof v==='object')return v;return JSON.parse(String(v))};
const bool=v=>v===true||String(v).toLowerCase()==='true'||String(v)==='1';
function build(name,row,map){let data={};const raw=value(row,map,'fullDocumentJson');if(raw)data=parse(raw,{});delete data._id;delete data.__v;delete data.createdAt;delete data.updatedAt;
 const set=(k,v)=>{if(v!==undefined&&v!=='')data[k]=v};
 if(name==='Products'){for(const k of ['legacyId','sku','productCode','slug','name','shortDescription','description','category','subCategory','currency','badge','hsnCode'])set(k,value(row,map,k));for(const k of ['price','oldPrice','stock','reservedStock','minOrderQty','maxOrderQty','weight','taxRate']){const v=value(row,map,k);if(v!==''&&v!=null)set(k,Number(v))}for(const k of ['active','featured','buyNowEnabled','addToCartEnabled','selfPickupAvailable','homeDeliveryAvailable','codAvailable','allowBackorder']){const v=value(row,map,k);if(v!==''&&v!=null)set(k,bool(v))}for(const [k,c] of [['tags','tagsJson'],['pickupLocationIds','pickupLocationIdsJson'],['primaryImage','primaryImageJson'],['gallery','galleryJson'],['features','featuresJson'],['specifications','specificationsJson'],['dimensions','dimensionsJson']]){const v=value(row,map,c);if(v!=='')set(k,parse(v,k==='specifications'||k==='dimensions'||k==='primaryImage'?{}:[]))}}
 if(name==='Orders'){for(const k of ['orderId','customerId','couponCode','currency','deliveryMode','pickupLocationId','paymentMethod','paymentStatus','orderStatus','confirmedAt','inventoryCommittedAt','invoiceId','customerVisibleNote','adminNote','idempotencyKey','trackingDetails','feedback','reviewText','feedbackTimestamp','paymentId'])set(k,value(row,map,k));for(const k of ['subtotal','discount','shippingCharge','taxAmount','grandTotal']){const v=value(row,map,k);if(v!==''&&v!=null)set(k,Number(v))}data.customerSnapshot={name:value(row,map,'customerName')||'',mobile:value(row,map,'customerMobile')||'',email:value(row,map,'customerEmail')||'',address:value(row,map,'customerAddress')||'',pincode:value(row,map,'customerPincode')||''};for(const [k,c] of [['items','itemsJson'],['pickupSnapshot','pickupSnapshotJson'],['trackingHistory','trackingHistoryJson']]){const v=value(row,map,c);if(v!=='')set(k,parse(v,k==='pickupSnapshot'?{}:[]))}}
 if(name==='Coupons'){for(const k of ['code','type','startAt','expiresAt'])set(k,value(row,map,k));for(const k of ['value','minOrder','maxDiscount','usageLimit','perCustomerLimit','usageCount']){const v=value(row,map,k);if(v!==''&&v!=null)set(k,Number(v))}const av=value(row,map,'active');if(av!==''&&av!=null)set('active',bool(av));for(const [k,c] of [['applicableProductIds','applicableProductIdsJson'],['applicableCategoryIds','applicableCategoryIdsJson']]){const v=value(row,map,c);if(v!=='')set(k,parse(v,[]))}}
 return data}
function productMedia(doc){return[doc?.primaryImage,...(doc?.gallery||[])].filter(Boolean)}
function managedKeys(media){const out=new Set();for(const meta of media){if(storage.isManagedSupabaseImage(meta))out.add(`${meta.bucket}:${meta.path}`);if(meta?.thumbnailPath){const thumb={bucket:meta.bucket,path:meta.thumbnailPath,url:meta.thumbnailUrl};if(storage.isManagedSupabaseImage(thumb))out.add(`${thumb.bucket}:${thumb.path}`)}}return out}
function removedProductMedia(before,after){const keep=managedKeys(productMedia(after));return productMedia(before).filter(meta=>{const keys=managedKeys([meta]);return[...keys].some(key=>!keep.has(key))})}
function validateProductMedia(data){const gallery=Array.isArray(data.gallery)?data.gallery:[];if(gallery.length>3||Number(Boolean(data.primaryImage?.url))+gallery.filter(x=>x?.url).length>4)throw Error('Product images must contain maximum 1 primary and 3 gallery images')}
async function importWorkbook(buffer){const wb=new ExcelJS.Workbook();await wb.xlsx.load(buffer);const result={products:0,orders:0,coupons:0,added:0,updated:0,deleted:0,skipped:0,imagesDeleted:0,imageCleanupFailed:0,errors:[]};
 for(const [name,cfg] of Object.entries(configs)){const ws=wb.getWorksheet(name);if(!ws)continue;const map={};ws.getRow(1).eachCell((c,i)=>{map[String(c.value||'').trim()]=i});if(!map.action||!map[cfg.key]){result.errors.push(`${name}: action and ${cfg.key} columns are required`);continue}
  for(let i=2;i<=ws.rowCount;i++){const row=ws.getRow(i);if(!row.hasValues)continue;try{const action=String(value(row,map,'action')||'').trim().toUpperCase();if(!ACTIONS.has(action))throw Error('action must be ADD, UPDATE, DELETE or SKIP');if(action==='SKIP'){result.skipped++;continue}const keyRaw=value(row,map,cfg.key),key=String(keyRaw||'').trim();if(!key)throw Error(`${cfg.key} is required`);const filter={[cfg.key]:name==='Coupons'?key.toUpperCase():key};const existing=await cfg.model.findOne(filter).lean();if(action==='DELETE'){if(!existing)throw Error(`${cfg.key} not found`);if(name==='Products'){const cleanup=await storage.removeMany(productMedia(existing));result.imagesDeleted+=cleanup.deleted.length;result.imageCleanupFailed+=cleanup.failed.length;if(cleanup.failed.length)throw Error(`Product was not deleted because ${cleanup.failed.length} managed image(s) could not be removed`)}await cfg.model.deleteOne(filter);result.deleted++;continue}const data=build(name,row,map);data[cfg.key]=filter[cfg.key];if(name==='Products')validateProductMedia(data);if(action==='ADD'){if(existing)throw Error(`${cfg.key} already exists`);await cfg.model.create(data);result.added++}else{if(!existing)throw Error(`${cfg.key} not found`);delete data[cfg.key];const before=existing;await cfg.model.updateOne(filter,{$set:data},{runValidators:true});if(name==='Products'){const after=await cfg.model.findOne(filter).lean(),removed=removedProductMedia(before,after),cleanup=await storage.removeMany(removed);result.imagesDeleted+=cleanup.deleted.length;result.imageCleanupFailed+=cleanup.failed.length;if(cleanup.failed.length)result.errors.push(`${name} row ${i}: product updated, but ${cleanup.failed.length} replaced image(s) need cleanup retry`) }result.updated++}result[name.toLowerCase()]++}catch(e){result.errors.push(`${name} row ${i}: ${e.message}`)}}}
 return result}
module.exports={backup,importWorkbook,configs};