const mongoose=require('mongoose');
const Product=require('../models/Product');
const safe=x=>String(x??'').trim();
const optional=x=>safe(x)||undefined;
function payload(body,{creating=false}={}){
  const out={slug:safe(body.slug).toLowerCase(),name:safe(body.name),sku:optional(body.sku)?.toUpperCase(),productCode:safe(body.productCode),category:safe(body.category),subCategory:safe(body.subCategory),tags:Array.isArray(body.tags)?body.tags.map(safe).filter(Boolean):[],price:Number(body.price),oldPrice:Number(body.oldPrice||0),badge:safe(body.badge),shortDescription:safe(body.shortDescription),description:safe(body.description),taxRate:Number(body.taxRate)||0,hsnCode:safe(body.hsnCode),weight:body.weight===''||body.weight==null?undefined:Number(body.weight),dimensions:body.dimensions||undefined,active:body.active!==false,buyNowEnabled:body.buyNowEnabled!==false,addToCartEnabled:body.addToCartEnabled!==false,featured:body.featured===true,selfPickupAvailable:body.selfPickupAvailable===true,homeDeliveryAvailable:body.homeDeliveryAvailable!==false,codAvailable:body.codAvailable===true,allowBackorder:body.allowBackorder===true,minOrderQty:Number(body.minOrderQty)||1,maxOrderQty:body.maxOrderQty===''||body.maxOrderQty==null?null:Number(body.maxOrderQty),features:Array.isArray(body.features)?body.features:[],specifications:body.specs||{}};
  if(creating){out.legacyId=safe(body.id||body.legacyId);out.stock=Number.isFinite(Number(body.stock))?Number(body.stock):0;out.reservedStock=0}
  if(safe(body.image)){out.primaryImage={url:safe(body.image),alt:out.name};out.gallery=(Array.isArray(body.gallery)?body.gallery:[body.image]).map((url,i)=>({url:safe(url),alt:out.name,sortOrder:i})).filter(x=>x.url)}
  return out;
}
function validate(v,{creating=false}={}){if(creating&&!v.legacyId)throw Object.assign(Error('Product ID is required'),{status:400});if(!v.slug||!v.name)throw Object.assign(Error('Slug and name are required'),{status:400});if(!Number.isFinite(v.price)||v.price<0)throw Object.assign(Error('Price must be a non-negative number'),{status:400})}
function duplicateMessage(error){const field=Object.keys(error?.keyPattern||error?.keyValue||{})[0]||'identifier';return `A product with this ${field} already exists. Please enter a unique value.`}
async function conflicts(v,excludeId){const or=[{legacyId:v.legacyId},{slug:v.slug}];if(v.sku)or.push({sku:v.sku});if(v.productCode)or.push({productCode:v.productCode});const q={$or:or.filter(x=>Object.values(x)[0])};if(excludeId)q._id={$ne:excludeId};return Product.find(q).select('_id legacyId slug sku productCode name').lean()}
async function create(body){const v=payload(body,{creating:true});validate(v,{creating:true});const before=await Product.countDocuments();const dup=await conflicts(v);if(dup.length)throw Object.assign(Error('A product with the same Product ID, slug, SKU, or product code already exists.'),{status:409,duplicates:dup});let created;try{created=await Product.create(v)}catch(e){if(e?.code===11000)throw Object.assign(Error(duplicateMessage(e)),{status:409});throw e}const after=await Product.countDocuments();if(after!==before+1){console.error('PRODUCT_COUNT_INVARIANT_FAILED',{before,after,createdId:String(created._id)});throw Object.assign(Error('Product was created but count verification failed. No cleanup was performed.'),{status:500})}return{product:created,before,after}}
async function edit(id,body){if(!mongoose.isValidObjectId(id))throw Object.assign(Error('Invalid product identifier'),{status:400});const current=await Product.findById(id);if(!current)throw Object.assign(Error('Product not found'),{status:404});const v=payload(body);validate(v);delete v.legacyId;delete v.stock;delete v.reservedStock;if(!safe(body.image)){delete v.primaryImage;delete v.gallery}const dup=await conflicts({...v,productCode:v.productCode},current._id);if(dup.length)throw Object.assign(Error('A product with the same slug, SKU, or product code already exists.'),{status:409,duplicates:dup});const count=await Product.countDocuments();try{Object.assign(current,v);await current.save()}catch(e){if(e?.code===11000)throw Object.assign(Error(duplicateMessage(e)),{status:409});throw e}if(await Product.countDocuments()!==count)throw Object.assign(Error('Product count changed during edit. Review concurrent writes.'),{status:409});return current}
module.exports={payload,validate,duplicateMessage,create,edit};